# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

apply = ['defer']

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ['source']

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit -i'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
use = ['{{ name }}.zsh']

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'

[plugins.F-Sy-H]
github = 'zdharma/fast-syntax-highlighting'

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.mise]
inline = 'eval "$(mise activate zsh)"'

[plugins.zoxide]
inline = 'eval "$(zoxide init zsh --hook prompt)"'

[plugins.gh]
inline = 'eval "$(gh completion -s zsh)"'

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"